import type { Metadata } from "next";
import { Geist } from "next/font/google"; // Only Geist
import "./globals.css";
import Navbar from "@/components/templates/Navbar";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={geist.variable}>
      <body className="min-h-screen">
        <div className="f-center p-3">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
